settings:
  username: "harshpandita2000"
  commit_msg: "ðŸ”¥ðŸš€ README UPDATED! ðŸš€ðŸ”¥"
  max_lines: 0
  readme_file: "README.md"
  disabled_events: [event1, event2, event3]
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+05:30"
    text: "<i>Last refresh</i> : <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
commit_name: "Schwifty-Bot"
 commit_email: "116818502+Schwifty-Bot@users.noreply.github.com" 
